### ISSUE TITLE
Error: The YAML file was not found. - which file?

### ISSUE THREAD

**Issue by chayev** [repowarden/cli#117]
When running `warden audit` an error message is thrown saying "Error: The YAML file was not found." however it's unclear which file is not found. Would be great if it specified which file is missing. 

<img width="462" alt="image" src="https://github.com/repowarden/cli/assets/18604081/d55bb348-bfb9-4f9a-9995-650b1d5bc72f">

**Comment by FelicianoTech** [comment]
I believe this to be the `policy.yml` file. There is a specific message for the repositories file. Thank.
